/** Términos y condiciones (mismo texto que contrato; TERCERA adaptada para cotización). */
export const TERMINOS_IMPORTANTE =
  'IMPORTANTE: TRASLADO O PASEO EXTRA NO ESPECIFICADO TIENE COSTO EXTRA Y TENDRA QUE SER LIQUIDADO AL MOMENTO DE REALIZARLO DIRECTO CON EL OPERADOR';

export const NOTA_RESERVA_COTIZACION =
  'Para reservar el servicio se requiere el 20% del total de esta cotización. El saldo restante (80%) deberá quedar liquidado al iniciar el servicio, al momento de la salida.';

export function getTerminosCotizacion() {
  return [
    `PRIMERA. Objeto. El "CLIENTE" contrata los servicios de "Recorriendo kilómetros SA de CV" a fin de que este último proporcione el servicio de transportación de pasajeros que detalla en la carátula.`,

    `SEGUNDA. "Recorriendo kilometros SA de CV" se obliga a mantener vigente la póliza de seguro de viajero por cada una de las unidades de transporte que utilice para dar el servicio materia del presente contrato, teniendo una cobertura de hasta 5000 UMA por pasajero, misma que cubre daños causados a los pasajeros durante el uso de la unidades de transporte hasta por dicho monto.`,

    `TERCERA: Pago y reserva: El "CLIENTE" se compromete a reservar el servicio descrito en la cláusula primera con el 20% del total de esta cotización. El saldo restante deberá quedar liquidado al iniciar el servicio, al momento de la salida. En caso de que "EL CLIENTE" solicite exceder el kilometraje respecto al servicio descrito en la primera cláusula, éste se obligará a liquidar previo a la realización de la extensión requerida las siguientes tarifas: Autobús Turístico de Lujo: $100 pesos por kilómetro excedido  Camion Tipo Escolar: $35 pesos por kilómetro excedido. Sprinter Mercedes Benz: $29 pesos por kilómetro excedido  Van Hiace o Urvan: $20 pesos por kilómetro excedido. Auto 4-6 plazas: $18 pesos por kilómetro excedido.`,

    `CUARTA. Conducta de los Usuarios. El "CLIENTE" se compromete a mantener en buen estado los interiores de las unidades y observar el buen comportamiento a bordo, así mismo, los pasajeros se abstendrán de fumar, ingerir bebidas alcohólicas o consumir enervantes o estupefacientes dentro de las unidades de "Recorriendo kilómetros SA de CV". El "CLIENTE" se obliga a indemnizar a "Recorriendo kilómetros SA de CV" de cualquier daño que ocurriera a las unidades por culpa, dolo o negligencia por parte de los pasajeros. El monto del daño será facturado por "Recorriendo kilómetros SA de CV" anexando la cotización del proveedor que lleve a cabo la reparación.`,

    `QUINTA. "Recorriendo kilometros SA de CV" se reserva el derecho de la subcontratación en el caso que así se requiera para cubrir un servicio y/o emergencias o imprevistos. En caso de la subcontratación para cubrir algún servicio, "Recorriendo kilómetros SA de CV" es responsable y está obligado a cumplir con el servicio estipulado en el presente contrato en igualdad de condiciones.`,

    `SEXTA: Derechos y Obligaciones."Recorriendo kilometros SA de CV" se obliga a: Asignar la unidad contratada en el lugar, fecha y hora estipulados en la cláusula primera.Asignar unidades en buenas condiciones mecánicas de higiene y seguridad. Reemplazar por unidades similares a las contratadas en caso de descompostura en un plazo máximo de dos veces el tiempo del recorrido del punto donde haya sucedido la descompostura respecto a la base de "Recorriendo kilómetros SA de CV" en Guadalajara.`,

    `"Recorriendo kilometros SA de CV" tiene el derecho de: Suspender el servicio en caso de que esté en riesgo la integridad de los pasajeros y/o de la unidad que brinda el servicio de transporte mencionando de forma enunciativa más no limitativa: Camino en mal estado, brechas angostas, tramos en reparación con alto riesgo, zonas con riesgo de delincuencia, inundaciones o deslaves, bloqueos o accidentes y demás situaciones que estén fuera del control de "Recorriendo kilómetros SA de CV". Suspender el servicio en caso de mal comportamiento dentro de la unidad de transporte por parte de los pasajeros tales como disturbios, riñas, consumo de drogas, alcohol, comportamientos inmorales, entre otros. En caso de que un pasajero o grupo de personas irrumpiera el servicio en un lugar intermedio por causas no imputables a "Recorriendo kilómetros SA de CV", el "CLIENTE" no tendrá derecho a reembolso alguno. "Recorriendo kilómetros SA de CV" no se hace responsable por objetos olvidados, perdidos o robados dentro de la unidad del servicio de transporte durante ni después del recorrido, tampoco se hace responsable por pérdidas de conexiones de vuelos o por tierra de los pasajeros. La responsabilidad de "Recorriendo kilómetros SA de CV" ante cualquier imprevisto no podrá ser superior al valor total del servicio descrito en la primera cláusula. El "CLIENTE" se obliga a: No exceder la capacidad de las unidades asignadas para el servicio descrito en la cláusula primera, en caso de hacerlo, "Recorriendo kilómetros SA de CV" no se hace responsable de ningún daño ocurrido a los pasajeros durante el servicio. Que los pasajeros se encuentren en el lugar acordado con un máximo de tolerancia de media hora de retraso respecto a la hora de salida y regreso de los lugares de origen, destino o trayectos intermedios que se visiten asignados en los detalles del servicio de la cláusula primera.`,

    `SÉPTIMA. Convienen ambas partes en que en el presente contrato no existe lesión, dolo, error, violencia o coacción alguna. Para todo lo relativo a la interpretación, cumplimiento y ejecución del presente contrato, las partes acuerdan someterse a la jurisdicción de los tribunales de la Ciudad de Guadalajara Jalisco, renunciando por lo tanto a cualquier fuero que pudieran tener en razón de sus domicilios actuales o futuros, señalando para recibir cualquier aviso o notificación al respecto, sus domicilios asentados en las Declaraciones de este contrato.`
  ];
}
